_wandb:
    value:
        cli_version: 0.23.0
        e:
            j1juhze2w35u216uqv4zm9oxqfyk0knx:
                codePath: scripts/train.py
                codePathLocal: scripts/train.py
                email: ace40@duke.edu
                executable: /opt/anaconda3/bin/python
                git:
                    commit: 48ad589833d00438bc481bfef0018903aebc316b
                    remote: https://github.com/averyestopinal/Module3Project.git
                host: Averys-MacBook-Pro-3.local
                os: macOS-26.0.1-arm64-arm-64bit
                program: /Users/averyestopinal/Desktop/510/Project3/Module3Project/scripts/train.py
                python: CPython 3.12.7
                root: /Users/averyestopinal/Desktop/510/Project3/Module3Project
                startedAt: "2025-11-23T04:12:45.876273Z"
                writerId: j1juhze2w35u216uqv4zm9oxqfyk0knx
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 5
                - 53
                - 105
            "2":
                - 5
                - 53
                - 105
            "3":
                - 16
            "4": 3.12.7
            "5": 0.23.0
            "12": 0.23.0
            "13": darwin-arm64
dataset:
    value: cleaned coffee data
model_type:
    value: RandomForestRegressor
n_estimators:
    value: 100
